services:
  app:
    image: ruby:lts
    volumes:
      - myapp:/home/node/app
    build: .
    develop:
      watch:
        - action: sync
          path: ./koans
          target: /src/app/koans
volumes:
  myapp:
